### PR TITLE
Feature/footer component

### PR DESCRIPTION
**Pull request by vikasrohit**
@aselbie @nlitwin please let me if anything can be improved here.

Please note, the component, does not support showing the other nav items into primary menu yet because of the reason described [here](https://app.asana.com/0/95614844085038/98363824898715). Repeating the comment from asana:
If we try to maintain the current behaviour for mobile, it would be tightly coupled to the primary nav because current implementation assumes that on mobile, these other navigation items would be visible at certain place(997px) from the top. In fact that is hiding 'Blog' menu item from the Community heading.

### CODE REVIEW

**Comment by nlitwin** [comment]
For the social icons, we should be able to use just one .svg file per social icon now (not desktop/mobile versions), since we aren't using them as background images anymore. We can inline then in the html code or include them as a React component, passing in height, width, and even fill. See for reference here: https://github.com/appirio-tech/topcoder-app-r/blob/dev/src/icons/LevelDesignatorIcon.jsx and used here: https://github.com/appirio-tech/topcoder-app-r/blob/32fb5bd7037cdf7b4a74e2596c3ec2fcfc5b9283/src/components/MemberItem/UserInfo.jsx

**Comment by aselbie** [comment]
Hey @vikasrohit, I took the MenuBar as an example and had a number of small suggestions that seemed like they would be easier to communicate as a PR. Take a look at https://github.com/appirio-tech/react-components/pull/39.

- You are already calling ``handleResize`` in ``componentWillMount`` will mount, so we don't need to set the ``mobile`` property on the state. Then if we move the bind to the the other methods we can remove the constructor entirely.
- Destructuring for the props in ``render``
- Favor ``const`` over ``let``
- Using the ``classNames`` module
- Breaking the list items into their own function rather than nesting them inside the ``<ul>``
- Using computed (dynamic) property names on objects to work with the orientation class name
- Handled the orientation using a default prop and the ``PropTypes.oneOf()`` property to do enum values

Let me know if you have any questions or concerns about these techniques and changes.

**Comment by vikasrohit** [comment]
Thanks @aselbie for the bulleted items. I have cross checked and found the footer component following all of them. Actually, it is a stateless functional component, hence, using more concise pattern as suggested by React docs.

**Comment by vikasrohit** [comment]
@nlitwin Thats really good idea. However, when I tried to do the same with social icons, I found that we have different Path elements for different view. In other words, icons for the desktop and mobile are not differentiated by width,height,fill or stroke, rather they are differentiated by the Path. Does it make sense to use if-else block for handling that or adjust the icons such that they have same Path and differ only in terms of width,height,fill or stroke. @vic-appirio Need your help here.

**Comment by vikasrohit** [comment]
@nlitwin I tried to extract the social icons as component, however, somehow they are not scaling well with the width/height set. Can you please check what piece i am missing here?

**Comment by vikasrohit** [comment]
Current state of footer for non mobile view:
footer-non-mobile
Current state of footer for mobile view:
footer-mobile

**Comment by nlitwin** [comment]
Hmm it might be the viewbox. I think you can just leave it as the default. For the most part, I pretty much just changed this `width={ width || '20px' } height={ height || '20px' }` I think that's all we need

**Comment by nlitwin** [comment]
I'm also just adding the 'px' in the props, so we don't have to declare new variables `<DefaultUserAvatarIcon width={'60px'} height={'60px'}/>`

**Comment by vikasrohit** [comment]
Ohk. I thought I need to use width and height for setting the view box. And now it makes more sense to use 'px' in the width/height attributes because we don't need them for setting up the viewBox. Thanks Nick.

**Pull request merged**
