### PR TITLE
fix: support isRequired validator for numeric values

### PR DESCRIPTION
**Pull request by maxceem**
Fix for https://github.com/appirio-tech/react-components/issues/328

### CODE REVIEW

**Review by vikasrohit — APPROVED** [review]
LGTM

**Comment by vikasrohit** [comment]
@maxceem It seems the PR now has conflict, can you please resolve the conflict?

**Comment by maxceem** [comment]
@vikasrohit I've resolved conflicts. But PR is already merged.

**Comment by vikasrohit** [comment]
Oh, it might be stale page in my browser.

**Comment by maxceem** [comment]
> Oh, it might be stale page in my browser.

No, there was indeed the merge conflict, but I guess it appeared **after** the PR is already merged (and was causing by this PR merging, weird).

**Pull request closed without merging**
