### PR TITLE
Fixed Issue #1155 sidebar links consistency

### PR DESCRIPTION
**Pull request by chq-matteo**
[Issue #1155](https://github.com/appirio-tech/topcoder-app/issues/1155) added a function to get the domain (production, dev, ...) and added href reflecting [footer.jade](https://github.com/appirio-tech/topcoder-app/blob/dev/app/layout/footer/footer.jade).

### CODE REVIEW

**Comment by tladendo** [comment]
@chq-matteo Instead of programmatically determining to URL you should use props like MAIN_URL that are used elsewhere in the app

**Comment by chq-matteo** [comment]
@tladendo I get the domain name from the main url
`+    const domain = SideBarFilters.domainFromUrl(this.props.config.MAIN_URL);`
I do that because I need to access the help. sub domain

**Comment by tladendo** [comment]
@chq-matteo when I try to run this code, nothing loads and I get an error that looks like: "SideBarFilters.jsx:658Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined(…)". Can you take a look?

**Comment by chq-matteo** [comment]
Sure

**Pull request merged**
