### PR TITLE
Fix for issue# 2857 on connect-app

### PR DESCRIPTION
**Pull request by akumar1503**
- Bottom link is now clickable in WizardRight.
 - Continue button fix in RegistrationScreen, it's not required to click the "I agree to receive other communications from Topcoder." checkbox.
 - removed + sign requirement in phone numbers in Formsy.PhoneInput.

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
Everything works good @akumar1503 .

Only one thing, could you please return adding `+` when we choose the county code in the dropdown.
We don't require entering `+` by users, but we still want to add `+` when we choose the country code.

**Comment by akumar1503** [comment]
@maxceem done.

**Comment by akumar1503** [comment]
added minor correction, done now.

**Review by maxceem — CHANGES_REQUESTED** [review]
Works good!

Thank you @akumar1503

**Comment by maxceem** [comment]
@RishiRajSahu I've tested this PR to cover 3 issues listed here https://github.com/appirio-tech/connect-app/issues/2857

It works good for me.
It can be merged separately from changes in Connect app.

**Pull request merged**
