### PR TITLE
AS#108326934861720, Add QA and Prod builds for react-components

### PR DESCRIPTION
**Pull request by vikasrohit**
@nlitwin @aselbie @parthshah @samsep 

Please let me know if any of you think that it would not be appropriate to have separate env. IMO, we should have separate envs because we can't use versioning system only for testing on local and dev. Because we would get CORS errors, in local/dev/qa, when we deploy bundles in same bucket (components.topcoder.com).

Also, please note that I haven't added actual key/secret for qa and prod yet. They are dummy values. If any of you have them for those env, please feel free to update them in the same branch.

### CODE REVIEW

**Comment by nlitwin** [comment]
Sounds good to me

**Comment by vikasrohit** [comment]
Thanks @nlitwin

**Comment by vikasrohit** [comment]
BTW, do you have know which AWS key/secrets we are using for other repos for qa/prod environments?

**Comment by nlitwin** [comment]
I've been just taking the ones listed in the Jenkins config for topcoder-app haha!

**Comment by vikasrohit** [comment]
Thanks. I would copy them from there too. :grin:

**Pull request merged**
