### PR TITLE
Final Fixes - Progress Bar Component

### PR DESCRIPTION
**Pull request by amolskh**

### CODE REVIEW

**Comment by vikasrohit** [comment]
@amolskh Can we get rid of two circles in case of only two checkpoints? Or have that configurable if we want to show/hide the circles for checkpoints (only when there are only two checkpoints)?

**Comment by vikasrohit** [comment]
Also, I just noticed that blue(completed) portion of the progress bar has round edge in specks. Is it something that you can achieve quickly?

**Comment by amolskh** [comment]
Added new config to hide circles

**Comment by vikasrohit** [comment]
Thanks @amolskh Accepted. Merging.

**Pull request merged**
