### PR TITLE
Need slider component for our project form questions #3159

### PR DESCRIPTION
**Pull request by suppermancool**
Need slider component for our project form questions #3159

### CODE REVIEW

**Comment by maxceem** [comment]
Hey @suppermancool 

I've noticed that in this PR you've referenced file `Formsy/SliderStandardExample.jsx` in the `Router.jsx`, but there is no such file in the repository.

image

So if I try to run `npm run dev` there is an error during building:

image

Could you please, help me to understand the best way to deal with it. Did you forget to include that file into this PR? Or should I just revert the changes in `Router.jsx` file?

Thanks.

**Comment by RishiRajSahu** [comment]
@suppermancool I think we missed revert the changes in Router.jsx during this commit https://github.com/appirio-tech/react-components/pull/322/commits/31484b8a2a8e5bd69d2695b897c6413170a7aed0 . 

@maxceem are we following the pattern of having example of every component in this repo, if yes, we can ask @suppermancool to bring back the example to the repo, else we can revert current changes from Router.jsx ?

**Comment by suppermancool** [comment]
@maxceem @RishiRajSahu ah sorry i removed that code but forget to commit

let me create MR for that

**Comment by maxceem** [comment]
> @maxceem are we following the pattern of having example of every component in this repo, if yes, we can ask

I guess we don't have strict requirements for the examples, though sometimes it's nice to have them to make quick validation. 

**Updated** ~I'm not sure what was the reason for deleting the existent example. If it's much efforts to keep it, probably I guess deleting is ok. Though if it's not hard to keep, then it would be nice to have it.~

Ah, it wasn't existent example it was an example which has been created and after deleted during working on this PR. Then as for me it's fine without an example of this component.

**Comment by suppermancool** [comment]
@maxceem @RishiRajSahu 
Done in https://github.com/appirio-tech/react-components/pull/326

The reason i removed the example because the SliderRadioGroup and SliderStandard use 'rc-slider', this component should be installed by the project that use `react-components` to avoid conflict of two 'rc-slider' version.
This mean these 2 components can't be run in react-components project itself. I just follow the way SliderRadioGroup does, and use for SliderStandard

**Comment by suppermancool** [comment]
Actually i already created the example but after figure out the problem with  'rc-slider' version , i reverted all the code

**Comment by maxceem** [comment]
Got it @suppermancool, thanks for clarifications.

**Pull request merged**
