### PR TITLE
Fix #1177

### PR DESCRIPTION
**Pull request by chq-matteo**
1. [Issue #1177](https://github.com/appirio-tech/topcoder-app/issues/1177)
2. Fixed expand button logic
3. Fixed keywords filtering logic
4. Fixed removed the use of Object.values() for compatibility [see](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values#Browser_compatibility)

### CODE REVIEW

**Comment by tladendo** [comment]
@chq-matteo 2 problems:
- when the filtering works, I often see an `Uncaught TypeError: Object.values is not a function` error in the console
- for some tags, like `C++` and `C`, the filtering doesn't work -- why is this?

**Comment by chq-matteo** [comment]
I'll look into it

**Comment by chq-matteo** [comment]
The c++ issue is due to wrong logic in the expansion of the technology tags, and caused by this pull
https://github.com/appirio-tech/react-components/pull/215/

**Comment by chq-matteo** [comment]
Basically it just looks for a '+' sign to check if it is the expansion button

**Comment by chq-matteo** [comment]
The other issue too seems to be preexisting and not related to these commits, I need a bit of testing to locate the exact code which causes it

**Comment by tladendo** [comment]
@chq-matteo if you can fix these related issues as part of this one we'll increase the prize on this ticket -- sound good?

**Comment by chq-matteo** [comment]
Sure :)

**Comment by chq-matteo** [comment]
I'll mention you when the patches are ready

**Comment by chq-matteo** [comment]
There was a problem with how keywords are processed in the filter, fixed adding spaces before and after the keyword to match. The C tag was working but every single contest with a 'c' somewhere in his content matched the filter

**Comment by tladendo** [comment]
@chq-matteo this is ready now, right?

**Comment by tladendo** [comment]
actually after looking at the code, it looks like you're still working on the console error, is that right?

**Comment by chq-matteo** [comment]
Yes there are multiple parts of code that have to be change.

**Comment by chq-matteo** [comment]
@tladendo I think I've solved all three issues.

**Comment by chq-matteo** [comment]
@tladendo I think that Object.values() went unnoticed because it is compatible with chrome and firefox and because that function was rarely used before the tag update.

**Comment by tladendo** [comment]
@chq-matteo looks good now!

**Comment by chq-matteo** [comment]
Good!

**Pull request merged**
