### PR TITLE
Progress bar component

### PR DESCRIPTION
**Pull request by amolskh**
Please  review and let me know if any changes required

### CODE REVIEW

**Comment by vikasrohit** [comment]
Awesome stuff @amolskh I would do detailed review tomorrow. However, after quick review of the functionality required for #51 here are some points:

1. Need one example when there is no checkpoint to fulfill requirement 'Without checkpoints there would be no checkpoint circles' and just show progress label (e.g. 60%) in place of date labels.
2. It is not a requirement, rather it is just a question out of curiosity. I see you have implemented the progress bar a vertical stack of three components i.e. checkpoint names, the progress bar and in last the progress labels (dates). Just to understand the merits and demerits, why you didn't choose to implement it as stack of horizontal elements where each element would be a vertical stack of checkpoint name, progress bar and progress label(date). I would like to know the what were your initial thoughts about it and how did you decide your strategy here. :)

**Comment by amolskh** [comment]
1. If there are no checkpoints where will be progress label should be placed? I understand progress label were part associated with checkpoint
2. Only advantacge i can think is laying out smooth horizontal lines.. If we use vertical one and text overflows I guess that will distort the middle line joining .. Joining middle lines and circle from 3 different div could after result some issues So horizontal line should be made 1 div that was idea

**Comment by vikasrohit** [comment]
Actually single answer would serve both points here. The advantage of using horizontal stack of checkpoints would be that each individual section (which we can have as sub component) i.e. one checkpoint to another (and if there is no checkpoint start and end would be two checkpoints) would have its own progress bar and to connect two such sections we are using cricles with some gap between progress bars and the circle, so we should not have problem of joining them smoothly. Now, each section/component, can have a property to display its progress under the bar. So, when there would be no checkpoint, we would have only such sub component. When there are multiple checkpoints, we can have each section to display its own progress or just aggregate the percentage completion of each checkpoint and show it on currently in progress checkpoint.
It might seem bit complicated, but I was just wondering around the possibilities and came up with this possibility.  :smile: 
@nlitwin what do you think?

**Comment by vikasrohit** [comment]
@amolskh How do you think we can achieve showing of progress label below the bar? IMO, we should have two components out of your current ProgressBar component. One would be actual progress bar which can show/hide progress label and another would be timeline component, which would reuse progress bar and add checkpoints to it to achieve the final timeline. I am not able to see it possible with vertical stack. What are your thoughts?

**Comment by amolskh** [comment]
Checkpoint based labels can be achieved in current design right?

Now labels without checkpoint . I am just trying to understand where should those labels be places in what distance?

**Comment by vikasrohit** [comment]
Checkpoint labels are already there in the form of dates.
We need label to show how much percent the work has been completed. Think it like reusing the component for showing file upload progress. How would you achieve that with current implementation?

**Comment by amolskh** [comment]
Cant really find a place to show that.. May be on hover over bar some kind of message popup i can think of

**Comment by vikasrohit** [comment]
How much efforts do you think it would take you to convert it to horizontal stack based implementation which would involve extracting the logic into two components ProgressBar and Timeline? We can increase the complexity to large of this task to accommodate that.

**Comment by amolskh** [comment]
Ok I can split it into 2 Component.  Would be gr8 if you can explain timeline component in detail

**Comment by vikasrohit** [comment]
What my idea is that progress bar would be a simple horizontal bar with option to show the progress label just below the completed portion of the bar. On the other hand, Timeline would be a component which would combine checkpoints with progress bar. For the simplest case, there would be two checkpoints and Timeline component would render first checkpoint as vertical stack of checkpoint label, circle and checkpoint label (which can be either percentage of completion for that checkpoint or a simple date label as we have right now). Then it would render the progress bar horizontally after the first checkpoint. And in the last it would render the last checkpoint in similar way it rendered the first one. And I think we can continue on rendering in this way for more checkpoints. However, you have to be careful about boundary cases i.e. when there is no or only one checkpoint specified for the timeline.
Please let me know if you think it can create any problem.

**Comment by amolskh** [comment]
"Then it would render the progress bar horizontally after the first checkpoint."  - Why after first checkpoint?

"you have to be careful about boundary cases i.e. when there is no or only one checkpoint specified"  What is difference in his scenario

**Comment by vikasrohit** [comment]
Have you started to work on this?

**Comment by amolskh** [comment]
Not full fledged.. Let me know if I need to start

**Comment by vikasrohit** [comment]
Then leave it for now. We would analyze it further and create new task for it in next challenge, if required. Thanks for your hard work. However, please include one more example with only two checkpoints.

**Comment by amolskh** [comment]
sure will do..

**Comment by vikasrohit** [comment]
Merging. Will put final fix list soon.

**Pull request merged**
