### PR TITLE
Add navbarDropdown component

### PR DESCRIPTION
**Pull request by reynard2007**
Implementation of #4

### CODE REVIEW

**Comment by vikasrohit** [comment]
@reynard2007 Can we close this?

**Comment by reynard2007** [comment]
Not yet please. I found some things I need to fix to make it more reuse friendly. I'm working on it alongside #8.

**Comment by vikasrohit** [comment]
@reynard2007 my concern is that there are two PR for the same issue. We need to close one of them.

**Comment by reynard2007** [comment]
Sorry, I forgot about this. yes, you may go ahead and close this PR.

**Comment by vikasrohit** [comment]
Closing.

**Pull request closed without merging**
