### PR TITLE
Implement dropdown component

### PR DESCRIPTION
**Pull request by reynard2007**

### CODE REVIEW

**Comment by reynard2007** [comment]
#4 pull request

**Comment by vikasrohit** [comment]
@reynard2007 I am getting following errors while running your code

`Uncaught Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.invariant @ invariant.js:39`

**Comment by vikasrohit** [comment]
Also, can you please rename the component to have generic name, like Dropdown instead of NavbarDropdown

**Comment by vikasrohit** [comment]
@reynard2007 I have managed to get it working on my local machine, however, the menu pointer is not showing at the correct location, it is always rendered in the top right of the example page, despite of the fact that the width of the dropdown-header is less than full page width.

So, todo list for now is:
- Rename NavbarDropdown to Dropdown
- Make the NavbarDropdownExamples page working (there are some sytax errors in that page which are causing the error I mentioned in previous comment.)
- Check the placement of the menu pointer. It would be great if you can put multiple dropdowns in the example page which shows different configuration usage of the component. e.g. dropdown without menu pointer, dropdown with full width, dropdown with limited width etc.
- Dropdown should close itself, when mouse is clicked outside of the component e.g. if user clicks anywhere on the page (outside of the dropdown), it should close the dropdown list.
- Put a demo for showing the usage of the dropdown where dropdown is rendered in the specified element of the DOM.

**Comment by reynard2007** [comment]
Just read the last comment after I pushed a fix for the invariant error. The dropdown appears to be full-width because the parent container is 100% and the dropdown is styled at 96% width. Do I assume that unless the dropdown style is overriden (e.g. in the UserDropdownMenu), it should have the same width as its parent?

**Comment by vikasrohit** [comment]
Yes, I think dropdown-menu-list width should match the width of the dropdown-header.

**Comment by vikasrohit** [comment]
Yes, I think dropdown-menu-list width should match the width of the dropdown-header.

**Comment by vikasrohit** [comment]
@reynard2007 We have just introduced the linting in the dev branch which would validate the source code for some code styles to have new code in sync with existing ones. Your last change in PR failed checks because of lint task failure, please check the lint errors and kindly resolve them in your next commit in this PR.

**Comment by reynard2007** [comment]
Hi @vikasrohit, will do the requested changes to pass the linting. My concern is that with the ongoing changes/updates, we might not meet the less than two days left for the challenge. Will try to double time tomorrow to get more tasks done, but wanted to know if this can be extended if need be.

**Comment by vikasrohit** [comment]
Thanks @reynard2007 for fixing the lint errors. We would really like to have the tasks completed by Thursday (EST) end of the day so that we have at least one day in this week to review the results and start integrating them with the main application. However, if you think you will need a day more, assuming that we have all tasks taken up by some member, we may think on it. In other words, lets say you or any other member is working on the full NavBar component and all other tasks are completed (at least merged into dev), and you need a day more, we can think of it. But if we are not sure that extending a day might not result in completion of all tasks, it would be really difficult to extend.
When do you think, you will be able to finish other tasks, considering the serial nature of tasks?

**Comment by reynard2007** [comment]
I think the remaining time is enough right now, but that is assuming no more dev updates are made aside from the merges, lest the need to revisit previous tasks. Already getting the hang of the new standard now, so it can only be easier from hereon in. Will let you know of any challenges, nevertheless.

**Comment by vikasrohit** [comment]
Ok. Thanks for your feedback.

BTW, Awesome work!! I just saw the examples page of the dropdown component and it looks good to me. Only thing that is missing is the ability to render the dropdown content in any other element of the DOM instead of rendering it just below the dropdown header. However, if you think that it would consume significant time right now, we can get it fixed later on as final fix.
Another thing is that can we have the ability to configure the location of the menu pointer to be on left or  right?

**Comment by reynard2007** [comment]
Thanks!

As for rendering it on any other element, I know you already explained that on another comment, but I think I'd need a spec for how that should look.

I'll push a new commit for the configurable arrow positioning. Can I make right default and we can just add an arrow-left property to override default?

**Comment by vikasrohit** [comment]
Actually, we don't have specks for that requirement. We are trying to make the component configurable in such a way that allow us to render it more elegantly on mobile devices. We are still not sure how we would render it finally on mobiles, however, with this ability we can configure it to show the dropdown in a div which itself is located some where else in the page's DOM. Basically, that means that we have some property in the component that takes in the css class or id of the element where we need to render the dropdown and when user clicks on dropdown header, it renders the dropdown in that element.
e.g. in the following image, on clicking on the hamburger icon (which is essentially the user dropdown component that you are working on) in the top right corner, would render the dropdown content as inline item after the nav bar instead of showing it as overlay on top of the page's content.
nav-scale-mobile-375-user

**Comment by vikasrohit** [comment]
Your assumption is correct for the default value of the menu pointer place.

I can merge your changes(after menu pointer place configuration) right away. We can handle the requirement of rendering it other element, in final fixes.

**Comment by vikasrohit** [comment]
@reynard2007 Can you please resolve the conflict? I think we would get some more conflicts as we merge other PRs.

**Comment by reynard2007** [comment]
Hi @vikasrohit, this is acknowledged and apologies for the delay in response. Will push a new commit by AM PHT tomorrow.

Just let me know when you find anything that needs fixing/resolving.

**Comment by reynard2007** [comment]
Submitted new PR at <https://github.com/appirio-tech/react-components/pull/30> for this Task. You may close this PR as needed.

**Comment by vikasrohit** [comment]
Thanks @reynard2007

**Pull request closed without merging**
