### PR TITLE
fixed appirio-tech/topcoder-app/issues/1131 corrected api url in props

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed appirio-tech/topcoder-app/issues/1131 corrected api url in props

### CODE REVIEW

**Comment by shubhendusaurabh** [comment]
https://github.com/appirio-tech/topcoder-app/issues/1131

**Comment by tladendo** [comment]
@shubhendusaurabh it looks like your code eliminated one console error, but i still see "Uncaught (in promise) TypeError: Failed to fetch(…)" two times when I run this locally in the dev environment. Can you take a look?

**Comment by shubhendusaurabh** [comment]
@tladendo can you share the URLs for which fetch is failing? I don't see any fetch errors in my console anymore.
console

**Comment by tladendo** [comment]
@shubhendusaurabh This is when you load the /listings page within topcoder-app.

**Comment by shubhendusaurabh** [comment]
@tladendo Created new PR https://github.com/appirio-tech/react-components/pull/186

**Pull request merged**
