### PR TITLE
Fix bug 1186

### PR DESCRIPTION
**Pull request by royshouvik**
This pull request fixes most of the issues mentioned in [bug 1186](https://github.com/appirio-tech/topcoder-app/issues/1186). The number of winners is less wrong now, but would need update on the V3 API to be absolutely correct. Fixes appirio-tech/topcoder-app#1186

### CODE REVIEW

**Comment by tladendo** [comment]
@royshouvik The code to get the real user avatar that you added doesn't seem to work for me. All profiles are showing the placeholder. Is it working for you?

**Comment by royshouvik** [comment]
@tladendo I tested this against the PROD backend and it was working fine for me. I am guessing that we don't have profile images for most of users in dev. Can you please try running against the prod backend and check if it still doesn't work for you?

**Comment by tladendo** [comment]
@royshouvik can you point the "results" link to the results page within challenge details?

**Comment by royshouvik** [comment]
@tladendo updated link to results page within challenge details

**Comment by tladendo** [comment]
@royshouvik on this one too: the past challenges page is coming up blank for me. any idea why?

**Pull request merged**
