### PR TITLE
fixes appirio-tech/topcoder-app/issues/1154 added upcoming challenges

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixes appirio-tech/topcoder-app/issues/1154 added upcoming challenges

### CODE REVIEW

**Comment by tladendo** [comment]
@shubhendusaurabh there's a hardcoded link to prod in this PR -- why?

**Comment by shubhendusaurabh** [comment]
@tladendo the file where hardcoded link is used is pure JS object. props cannot be used, something like process.env can be used  but will require changes like in #213 to be merged first.

**Comment by tladendo** [comment]
@shubhendusaurabh I'll do this one after merging that one, then

**Comment by shubhendusaurabh** [comment]
@tladendo updated

**Comment by tladendo** [comment]
@shubhendusaurabh can you merge the latest into this? i can bump the prize up a bit, and count it towards your total :)

**Comment by shubhendusaurabh** [comment]
@tladendo latest 'tom-styling-fixes' branch? Merged

**Comment by tladendo** [comment]
@shubhendusaurabh thanks!

**Pull request merged**
