### PR TITLE
issue3100 from connectapp Radio group option style breaks when there …

### PR DESCRIPTION
**Pull request by iversonLv**
…is very long text for the radio group option

PR for https://github.com/appirio-tech/connect-app/issues/3100

@maxceem

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks @iversonLv 

Looks almost perfect, the only thing it should be displayed in front of the first line of the label instead of the center of the label.

image

**Comment by iversonLv** [comment]
This is what we want? @maxceem 

[Screenshot from Gyazo](https://gyazo.com/f22b19287e90001cc8adf1e5198b83a0)

**Comment by iversonLv** [comment]
The radio will always at first line no matter how many lines for the label?

**Comment by iversonLv** [comment]
@maxceem done. Thanks.

**Comment by maxceem** [comment]
Sorry, for the late reply,
>  This is what we want? @maxceem

yes

> The radio will always at first line no matter how many lines for the label?

yes

Will check out the new PR.

**Review by maxceem — APPROVED** [review]
Works good now, @iversonLv.

**Comment by maxceem** [comment]
@vikasrohit I think this PR can be merged independently without waiting for other CF fixes.

**Comment by maxceem** [comment]
I'm closing this PR and will create another one as per requested change https://github.com/appirio-tech/connect-app/issues/3100#issuecomment-509090006

**Comment by maxceem** [comment]
Reopen this PR as per update https://github.com/appirio-tech/connect-app/issues/3100#issuecomment-509092402

@vikasrohit I think this PR can be merged independently without waiting for other CF fixes.

**Pull request merged**
