### PR TITLE
Implement QuickLinks component

### PR DESCRIPTION
**Pull request by reynard2007**
Task #9

### CODE REVIEW

**Comment by vikasrohit** [comment]
@reynard2007 Can you please resolve the conflicts?

**Comment by reynard2007** [comment]
This is acknowledged. Will work on the merge conflicts after the other PR gets merged.

**Comment by vikasrohit** [comment]
@reynard2007 merged PRs for dropdown and user dropdown components. Do you need any other PR to be merged for this PR to be merged?

**Comment by reynard2007** [comment]
The PR for SeatchSugegstions which I am still resolving.

**Comment by vikasrohit** [comment]
I don't think we need that PR to be merged because Quick Links Dropdown component does not use any of the component developed under #7

**Comment by reynard2007** [comment]
I was worried that conflicts would arise on the NavContainer.coffee and Router.jsx files but will be working with this as well as requested.

**Comment by reynard2007** [comment]
Replaced by PR #33. Closing.

**Pull request closed without merging**
