### PR TITLE
removed open for review bucket #1170

### PR DESCRIPTION
**Pull request by chq-matteo**
[Issue 1170](https://github.com/appirio-tech/topcoder-app/issues/1170)

### CODE REVIEW

**Comment by tladendo** [comment]
can you modify this so the page doesn't navigate to a blank state before redirecting?

**Comment by chq-matteo** [comment]
Now it doesn't apply the filter before redirecting. I'm not quite sure of what you mean with blank state, at least in chrome it directly starts redirecting

**Comment by tladendo** [comment]
@chq-matteo this is what I mean by blank state: http://imgur.com/a/JiIX7

Actually, it doesn't even redirect for me now -- it just goes to this state.

**Comment by chq-matteo** [comment]
@tladendo Yeah sorry I should have checked better, It was missing a .mode

**Pull request merged**
