### PR TITLE
Fix tc 1189

### PR DESCRIPTION
**Pull request by royshouvik**
Fixes appirio-tech/topcoder-app#1189 and a related bug where completed First 2 Finish challenges are displayed as "Open for registration".

### CODE REVIEW

**Comment by tladendo** [comment]
@royshouvik Was there something available in prod or dev to test this on? Or should I create some design challenges in dev to verify?

**Comment by royshouvik** [comment]
@tladendo unfortunately there wasn't. I only checked the negative case i.e challenges whose checkpoint has not passed are displayed under "Open for registration". It would be nice if you can create some in DEV.

**Comment by tladendo** [comment]
@royshouvik it looks like this excludes all the challenges that have checkpoint submission as an upcoming phase. These shouldn't be excluded.

**Comment by tladendo** [comment]
@royshouvik shouldn't this one be excluded? https://www.topcoder-dev.com/challenge-details/30050696/?type=design

**Comment by royshouvik** [comment]
@tladendo This should be fixed now. Please check.

**Comment by tladendo** [comment]
@royshouvik the challenges that are being excluded now should be moved to "ongoing challenges" since they're not closed

**Pull request merged**
