### PR TITLE
fixed appirio-tech/topcoder-app/issues/1167 clean up constants

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed appirio-tech/topcoder-app/issues/1167 clean up constants

### CODE REVIEW

**Comment by tladendo** [comment]
@shubhendusaurabh please try to use props instead of `process.env`

**Comment by shubhendusaurabh** [comment]
Updated. process.env will still be required in setting default props as constants object is not present in react-components as they are present in topcoder-app.

**Comment by shubhendusaurabh** [comment]
@tladendo Did you review changes after your comment?

**Comment by tladendo** [comment]
@shubhendusaurabh you still have a direct ref to `process.env` in `UserDropdownMenuExamples.jsx `

**Comment by tladendo** [comment]
@shubhendusaurabh could you also try to make sure the right props are getting passed into the components, where possible? thanks

**Comment by shubhendusaurabh** [comment]
@tladendo Updated.

**Comment by tladendo** [comment]
@shubhendusaurabh added one last question in code comments

**Comment by shubhendusaurabh** [comment]
@tladendo What is the question? Can't find any.

**Comment by tladendo** [comment]
@shubhendusaurabh in `components/Navbar/NavbarExample.jsx`, why did you take `INTERNAL_API_URL` out of the props and drop the call to `process.env` right into the code?

**Comment by shubhendusaurabh** [comment]
@tladendo The function `suggest` in which `INTERNAL_API_URL` is being used is not part of the component. It is called by the child component with only search term passed in.

**Comment by tladendo** [comment]
@shubhendusaurabh is this supposed to work when running react-components by itself? because that's not working for me. updated webpack as well

**Comment by shubhendusaurabh** [comment]
@tladendo yes, it should. Did you restart webpack after updating. In my case I made the changes in `/react-components/node_modules/appirio-tech-webpack-config/webpack.config.coffee` file directly then worked on it.

**Comment by tladendo** [comment]
@shubhendusaurabh do challenge details page links work for you? that's where i'm seeing the problem

**Comment by shubhendusaurabh** [comment]
@tladendo Details link issue was present before my changes but I have fixed this now.

**Comment by tladendo** [comment]
@shubhendusaurabh thanks!

**Pull request merged**
