### PR TITLE
Wizard redesign - Checkboxes and radio buttons with optional description and price (without design update)

### PR DESCRIPTION
**Pull request by maxceem**
winning submission from challenge 30083737 - Topcoder Connect - Wizard redesign - Controls new design

+ fix to format prices with comma

This PR implements a part of form redesign which is now in https://github.com/appirio-tech/connect-app/tree/feature/form-redesign

After this PR is merged, we have to update dependency in connect app branch `feature/form-redesign`, to point back to `appirio-tech/react-components#feature/connectv2` instead of `maxceem/react-components#feature/connectv2-form-redesign`

### CODE REVIEW

**Comment by vikasrohit** [comment]
@maxceem can we merge this PR safely without affecting behaviour of current components? I mean if we merge it today and do a production deploy afterwards, would it cause any troubles with the way the form elements are rendered currently on production?

**Comment by maxceem** [comment]
@vikasrohit We only added new features but didn't break any existent features so this PR should be safe. 
But if we are not going to merge `feature/form-redesign` to `dev` and `master` today, we can skip merging this PR today. And merge it after release. Even though this PR should be safe, it would be better if we test it for some time on `dev` if possible.

**Comment by vikasrohit** [comment]
Okay. I would merge it after today's release. Thanks for the update.

**Comment by vikasrohit** [comment]
merging the PR @maxceem @RishiRajSahu

**Pull request merged**
