### PR TITLE
Issue 1534 connect app

### PR DESCRIPTION
**Pull request by maxceem**
Connect app issue [1534](https://github.com/appirio-tech/connect-app/issues/1534)

### Implementation notes
- Tooltip HTML markup is being created on `mouseEnter`/`click` and removed on `mouseLeave`/`clickOutside`
- Backward compatibility of Tooltip component.
  Tooltip examples which can be seen by running `npm run example` in `appirio-tech-react-components` are fully supported by the new implementation.

### TODO
- When reimplementing Dropdowns probably it makes sense to pick out some common part of current Tooltip implementation and reuse it for Dropdowns.
  Common part is event handlers. So basically Tooltip and Dropdown implementations have to have only different markup.

### CODE REVIEW

**Comment by birdofpreyru** [comment]
Can somebody brief me, why have you guys decided to use *Popper* for the new Tooltip implementation, and not the `rc-tooltip` package being used in Community App?

Also, the Dropdowns are quite more complex that just kind of a tooltip appearing in the necessary place. In Community App we use `react-select` that has a bunch of features (selection of single / multiple options, automatic suggestion of options when you type, etc.) Don't we want just to reuse that one?

**Comment by gondzo** [comment]
See this thread https://github.com/appirio-tech/connect-app/issues/1534
Basically it's about handling viewport edges and positioning the tooltip properly. Is that supported by rc-tooltip?

**Comment by birdofpreyru** [comment]
Hmm, ok, not sure about the viewport edges support by `rc-tooltip`. Indeed, it seems it does not provide this out of the box.

**Comment by maxceem** [comment]
Yeah, there were two main requirements for Tooltips:
- fit viewport when possible
- don't generate DOM elements for hidden tooltips

`rc-tooltip` was the first package I've checked but it doesn't support these requirements.

I've also checked `react-select` when updated Dropdown recently. But it's more replacement for `select` tag rather than drop-down menu. Probably it could be styled as regular dropdown but it looks like it's not intended for that purpose.

Btw Bootstrap v4 uses popper to implement their tooltips and dropdowns https://getbootstrap.com/docs/4.0/getting-started/introduction/

**Comment by birdofpreyru** [comment]
Just to be sure, what exactly are we calling the regular dropdown?

**Comment by maxceem** [comment]
We click on something and get some block shown next to it:
It can be a list of link/buttons:
http://take.ms/xyFrP
http://take.ms/MvZti
It can be more complex stuff like notifications:
http://take.ms/HDyt1n

**Comment by birdofpreyru** [comment]
OK, now i see the difference :)

**Comment by gondzo** [comment]
I'm not sure how to resolve the build issue

 `/home/travis/build/appirio-tech/react-components/navbar.webpack.config.coffee:1
(function (exports, require, module, __filename, __dirname) { webpackConfig = require 'appirio-tech-webpack-config'
                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected string`

any ideas @maxceem @vikasrohit

**Comment by maxceem** [comment]
I've removed `coffeescript` dependency which I've added previously so `npm run example` works. Now it doesn't work again without installing `coffeescript` package. Not sure why it brakes Travis as it works well locally with `coffeescript`.

**Comment by gondzo** [comment]
weird, I tried removing it locally and it was still failing on `npm run build-navbar`

**Comment by maxceem** [comment]
Oh, I've never tried to run `npm run build-navbar`.
Does it work now without `coffeescript` or there are any other issues?

**Comment by gondzo** [comment]
It does succeed (returns code 0), but it does print out some errors like 

`ERROR in Cannot find module 'coffeescript'
 @ multi TCNavComponents
Child html-webpack-plugin for "index.html":`

**Comment by maxceem** [comment]
Yea, it was **not** listed in dependencies, so I've added it during working on this issue to run examples for testing. But it started breaking CI.

Should we try to add it back find another way to fix CI issue? Or leave like it was before for now?

**Comment by gondzo** [comment]
IMO it has something to do with version of coffeescript that we add, but
I'm not sure how to figure out what is the correct version to use here.
Also, I'm not sure how the build was passing on CI if it never had the
coffeescript dependency.
I guess we can tackle this in a separate issue.

**Pull request merged**
